apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator
rules:
  # Права для работы с CRD и кастомными ресурсами MySQL
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["otus.homework"]
    resources: ["mysqls", "mysqls/status", "mysqls/finalizers"]
    verbs: ["get", "list", "watch", "patch", "update"]
  
  # Права для создания ресурсов (Service, PV, PVC, Deployment)
  - apiGroups: [""]
    resources: ["services", "persistentvolumes", "persistentvolumeclaims", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Права для работы Kopf (фреймворка оператора)
  - apiGroups: ["kopf.dev"]
    resources: ["clusterkopfpeerings", "kopfpeerings"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysql-operator
subjects:
  - kind: ServiceAccount
    name: mysql-operator
    namespace: default
