apiVersion: v2
name: homework-chart
description: A Helm chart for Kubernetes HW
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: redis
    version: 18.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
