apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  initContainers:
    - name: init-downloader
      image: busybox
      command:
        - /bin/sh
        - -c
        - |
          wget -O /init/index.html https://example.com
      volumeMounts:
        - name: shared-volume
          mountPath: /init
  containers:
    - name: main-server
      image: nginx
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: shared-volume
          mountPath: /homework
      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sh
              - -c
              - rm -f /homework/index.html
