apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-templating
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: Otus
  source:
    repoURL: <REPO_URL>
    targetRevision: HEAD
    path: kubernetes-templating/homework-chart
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: replicaCount
          value: "1"
  destination:
    server: https://kubernetes.default.svc
    namespace: HomeworkHelm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
