apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: Otus
  namespace: argocd
spec:
  description: Otus course project
  sourceRepos:
    - '*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
